### ISSUE TITLE
Final Output - IGV and Reconstructing Final Contigs

### ISSUE THREAD

**Issue by iek** [zhixingfeng/iGDA#3]
Hi Zhixing, I'm sorry for the additional questions, but I have two final ones regarding the output:

1. How did you group together the outputted contigs to the reference strain contigs in IGV like this:
<img width="938" alt="Screen Shot 2021-12-16 at 1 00 12 PM" src="https://user-images.githubusercontent.com/12649783/146424887-3067017c-6436-4019-ab2c-d91c6d5049ac.png">
 
2. In your iGDA output for the metagenome set of Borrelia, you said that you outputted 753 final contigs. If you didn't know what the metagenome set contained, how would you decipher which strains you have based on the 753 final contigs? Did you perhaps run an assembly on the contigs to try to determine the contained strains?

**Comment by iek** [comment]
It seems that for Pacbio, you used Pacbio's genome consensus module to decipher the strains from the final 753 outputted contigs. Does Nanopore have something equivalent?

**Comment by zhixingfeng** [comment]
Hi Isaac,
1. You could find the details on how to obtain the IGV snapshot in the example data in README.md. I copy the link here, https://www.dropbox.com/sh/umi03t3eendcktf/AADX96opFaRVf3aaUi7Xoocia/pacbio_meta/script?dl=0&preview=igda.sh&subfolder_nav_tracking=1 

Scroll down to the bottom, under comments, "follow the steps below to visualize the contigs by IGV (version 2.7.2)". 

2. iGDA only report unambiguously resolved strains or haplotypes. If two contigs are far away with each other (distance is way longer than read length), iGDA is not trying to infer whether the contigs are from the same strain due to the "model identifiability problem". It is technically possible to over this, but I believe the best bet is using strain-level binning techniques rather than assembling the reported contigs (iGDA have done a round of assembly internally, and report the unambiguous contigs or unitigs. An aggressive assembly might lead to chimeric errors, which incorrectly merge contigs from different strains).

**Comment by iek** [comment]
Hi Zhixing,

Thank you so much! Would you mind elaborating on what you mean by strain-level binning techniques? Thank you.

**Comment by zhixingfeng** [comment]
A binning techniques that can distinguish strains of the same species , like the methods using relative abundance of the distant contigs for binning. Some methods are not strain-level because they are using features like k-mer frequency, which cannot distinguish strains of the same species.

**Comment by zhixingfeng** [comment]
iGDA does NOT use the PacBio consensus module or any other PacBio code, and it works for both PacBio and Nanopore with different parameters.
